### PR TITLE
Auto refresh metrics every second

### PR DESCRIPTION
**Pull request by kulvind3r**
Wrapped the XHR request creation and send in a JS function and set the function to be called every 1s.

Makes all the metrics refresh automatically every second. Far easier to continuously see what is happening than manually refreshing the page repeatedly.

p.s: Github for some reason is showing stupid diff, all i did was move the entire code 1 level deeper in indention to put it inside the fetchMetrics function.

### CODE REVIEW

**Comment by Demion** [comment]
Works great. Thanks. 
I think problem is you use spaces instead of tabs for indentation and line endings LF instead of CRLF.
Also would be good to add check box to enable / disable auto refresh.

Update: end of lines are LF in both cases.

**Comment by kulvind3r** [comment]
Added an auto refresh checkbox and some styling to make it bit easy on the eyes. Also added a favicon.

**Comment by Demion** [comment]
Looks good. 
Please convert all indentations to tabs or spaces to be consistent (lines 72-239).

**Comment by kulvind3r** [comment]
Should be done now. I checked by doing a select all in my vs code and making sure all lines show the tab symbol and no spaces in indentation.

Whole mix and match happened because of using notepad++ on my remote server and vscode on my client desktop. 

I was making changes to the file on hosted server and testing it on client side, finally when it was correct i just copied the entire file and committed. =P

**Comment by Demion** [comment]
https://github.com/Demion/remotehwinfo/blob/68f37614a551f08587e72d7daea3f56bd275a684/index.html#L72-L74

**Comment by kulvind3r** [comment]
done

**Pull request merged**
